export const dynamic = "force-dynamic";

export async function GET() {
  const lines = [
    "# Robots.txt for Monsbah.com",
    "# Updated: November 2025",
    "",
    "# Default rule - Allow all crawlers",
    "User-agent: *",
    "Allow: /",
    "",
    "# Disallow private and system areas",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /_next/",
    "Disallow: /auth/",
    "Disallow: /*?*auth=",
    "Disallow: /*?*token=",
    "Disallow: /profile/",
    "Disallow: /company-profile/",
    "",
    "# Allow crawling of static assets",
    "Allow: /_next/static/",
    "Allow: /_next/image",
    "Allow: /public/",
    "",
    "# Googlebot - Full access",
    "User-agent: Googlebot",
    "Allow: /",
    "Crawl-delay: 0",
    "",
    "# Googlebot Image - Allow all images",
    "User-agent: Googlebot-Image",
    "Allow: /",
    "Crawl-delay: 0",
    "",
    "# Googlebot Mobile - Full access",
    "User-agent: Googlebot-Mobile",
    "Allow: /",
    "Crawl-delay: 0",
    "",
    "# Googlebot News - Focus on blog content",
    "User-agent: Googlebot-News",
    "Allow: /*/blogs/",
    "Allow: /*/blog/",
    "Crawl-delay: 0",
    "",
    "# Bingbot - Full access",
    "User-agent: Bingbot",
    "Allow: /",
    "Crawl-delay: 1",
    "",
    "# Block AI training crawlers (protect content)",
    "User-agent: GPTBot",
    "Disallow: /",
    "",
    "User-agent: ChatGPT-User",
    "Disallow: /",
    "",
    "User-agent: CCBot",
    "Disallow: /",
    "",
    "User-agent: anthropic-ai",
    "Disallow: /",
    "",
    "User-agent: Claude-Web",
    "Disallow: /",
    "",
    "# Main sitemap index (includes all locales)",
    "Sitemap: https://monsbah.com/sitemap.xml",
    "",
    "# Specialized sitemaps",
    "Sitemap: https://monsbah.com/sitemap-static.xml",
    "Sitemap: https://monsbah.com/sitemap-categories.xml",
    "Sitemap: https://monsbah.com/sitemap-companies.xml",
    "Sitemap: https://monsbah.com/sitemap-blogs.xml",
    "Sitemap: https://monsbah.com/sitemap-images.xml",
    "Sitemap: https://monsbah.com/sitemap-news.xml",
  ];

  return new Response(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=UTF-8",
      "Cache-Control": "no-store, no-cache, must-revalidate, proxy-revalidate",
      "Pragma": "no-cache",
      "Expires": "0",
    },
  });
}
